= Software & Electronics & Embedded
:nofooter:
:icons: font
:toc: left
:docinfo: shared-head

Notes on small hobby projects in the field sofware development, electronics design and embedded devices.

In addition to the https://github.com/vittali/vittali.ch[documentation repo],
each project has its compagnion github repo with source code and supporting material.
Please use the github issue tracker to provide feedback and corrections.

If not otherwise stated, this work is licensed under the terms of the MIT license.


Copyright (C) 2019 Peter Vittali

== Embedded devices

* https://vittali.ch/1-bbb-jtag[Getting started with the BeagleBone Black and the PRU via JTAG],
https://github.com/vittali/vittali.ch-1-bbb-jtag[compagnion repo].

== IoT (Internet of Things)

* https://vittali.ch/2-nred-bluemix[Getting started with Node-RED and the IBM bluemix cloud],
https://github.com/vittali/vittali.ch-2-nred-bluemix[compagnion repo].

* https://vittali.ch/st1[ST1: Getting started with the TI CC2650 Sensor Tag],
https://github.com/vittali/vittali.ch-gst.st1[git repo].

* https://vittali.ch/st2[ST2: Getting started with the TI CC1350 Sensor Tag],
https://github.com/vittali/vittali.ch-gst.st2[git repo].

== Abbreviations

IoT:: internet of things
TI:: Texas Instruments
RB:: Node-Red on Bluemix
BBB:: Beagle Bone Black
BLE:: Bluetooth Low Energy
MCU:: microcontroller

== Contact & Impressum

If you have questions or feedback please use the github issue tracker of the relevant project.
Alternatively, please send me an email:

++++
<form id="contactform" method="POST">
    <input type="text" name="name" placeholder="Your name">
    <input type="email" name="_replyto" placeholder="Your email">
    <input type="hidden" name="_subject" value="Website contact" />
    <textarea name="message" placeholder="Your message"></textarea>
    <input type="text" name="_gotcha" style="display:none" />
    <input type="submit" value="Send">
</form>
<script>
    var contactform =  document.getElementById('contactform');
    contactform.setAttribute('action', '//formspree.io/' + 'vittali' + '@' + 'sunrise' + '.' + 'ch');
</script>
++++

Peter Vittali +
Weidenweg 1 +
CH-4127 Birsfelden, Schweiz +
+41 61 271 89 33

== Legal

The content on this website may contain technical inaccuracies or typographical errors
and may be changed or updated without notice.
The authors of this website may also make improvements and/or changes to the content at any time without notice.

The authors of vittali.ch assume no responsibility
regarding the accuracy of the content and use of the content is at the recipients own risk.
The authors of vittali.ch provide no assurances that any reported problems with any content will be resolved.
