= Software & Electronic & Embedded
:nofooter:
:icons: font
:toc: left
:docinfo: shared-head
:includedir: _includes
:imagesdir: ./images
:source-highlighter: highlightjs
:sectnums:

Notes on small hobby experiments with software, electronic design and embedded devices.

Feel free to copy (MIT license).

Please use the github issue tracker for questions, feedback and corrections.



Copyright (C) 2019 Peter Vittali

== Embedded devices

* https://vittali.ch/1-bbb-jtag[Getting started with the BeagleBone Black and the PRU via JTAG]

== IoT (Internet of Things)

* https://vittali.ch/2-nred-bluemix[Getting started with Node-RED and the IBM bluemix cloud]

* https://vittali.ch/3-CC2650-ST[Getting started with the TI CC2650 Sensor Tag]

* https://vittali.ch/4-CC1350-ST[Getting started with the TI CC1350 Sensor Tag]

* https://vittali.ch/5-TIR-1002[TI Reference Design TIDC-01002: Sub-1GHz Embedded Sensor to Cloud Industrial Internet of Things(IoT) Gateway Reference Design]

== Contact & Impressum

++++
<form id="contactform" method="POST">
    <input type="text" name="name" placeholder="Your name">
    <input type="email" name="_replyto" placeholder="Your email">
    <input type="hidden" name="_subject" value="Website contact" />
    <textarea name="message" placeholder="Your message"></textarea>
    <input type="text" name="_gotcha" style="display:none" />
    <input type="submit" value="Send">
</form>
<script>
    var contactform =  document.getElementById('contactform');
    contactform.setAttribute('action', '//formspree.io/' + 'vittali' + '@' + 'sunrise' + '.' + 'ch');
</script>
++++

Peter Vittali +
Weidenweg 1 +
CH-4127 Birsfelden, Schweiz +
+41 61 271 89 33

== Legal

The content on this website may contain technical inaccuracies or typographical errors
and may be changed or updated without notice.
The authors of this website may also make improvements and/or changes to the content at any time without notice.

The authors of vittali.ch assume no responsibility
regarding the accuracy of the content and use of the content is at the recipients own risk.
The authors of vittali.ch provide no assurances that any reported problems with any content will be resolved.
