[bibliography]
=== TI E2E support forum

==== dicussions started by the author

- [[[e2e1]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/822386[CC2650STK: SensorTag doesn't show up in device list of TI SensorTag App]
* choosing the right app: the flyer in the box mentions an app that is not available anymore, the _SimpleLink SensorTag_ on Google Play is the correct one, although the CC2650STK is not part of the SimpleLink family
* granting permissions: for some reason you must grant access to your phone's location. This is not only annoying because this is supposed to be demo software,
but also the app doesn't work without warning if you don't grant access.

- [[[e2e2]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/828436[CC2650STK: Cloud Settings for the IBM IOT platform for BlueMix Free]
* currently the IBM Watson IoT platform access (as opposed to the IBM Quickstart access) is not available with the _SimpleLink SensorTag_ app due to a bug.

- [[[e2e3]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/831544[CC2650STK: Is there a linux compatible BLE stack for the CC2650STK]
* no, this is one of the idiosyncrasies of the CC2650STK, refer to the {rTI-3} for a Linux compatible BLE development environment.

- [[[e2e4]]] https://e2e.ti.com/support/tools/ccs/f/81/t/828577[CCS/CC2650STK: Failed to launch debug session for CC2650STK]
* contrary to what the discussion suggests, the target configuration of the _uartecho_CC2650STK_ project is correct, no modification is required.
* contrary to what the discussion suggests, the {rTI-5} is currently not supported for the Sensor Tags, use the {rTI-6}.
* contrary to what the discussion suggests, the coin battery must not be inserted during debugging, the target is powered by the {rTI-6}.

- [[[e2e5]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/827756[CCS/CC2650STK: Can I use CCS and the XDS110 debug probe to program and debug the CC2650STK SensorTag]
* while it is possible to connect the {rTI-5}, see Figure <<JTAG>>, this debug probe is currently not supported for the Sensor Tag.

- [[[e2e6]]] https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/832998[CC1350STK: Downloading new firmware images to the device via the Over-the-Air-Download (OAD) service not as described in doc]
* applies to the CC2650 SensorTag and {rTI-3}: this is bug _SimpleLink SensorTag_ app.

- [[[e2e7]]] https://e2e.ti.com/support/tools/ccs/f/81/p/831543/3077956[CCS/CC2650STK: Can't start the System Analyzer despite the README.md saying so]
* see chapter <<logging>>

- [[[e2e8]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/831951[CC2650STK: Can't use UART on CC2650 STK]
* this was due to the usage of the {rTI-5} debug probe in conjunction with the suggested modification of the target configuration file in <<e2e5>>.
The usage of the uart is demonstrated in the <<uartecho_CC2650STK_TI>> as shown in this tutorial.

- [[[e2e9]]] https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/837456[ CC1350STK: Where is the out-of-box demo source code for the CC1350 and CC2650 Sensor Tags ?]
* another idiosyncrasy of the the CC2650STK and the CC1350STK: the out-of-box demo source code is not available. Why ?

- [[[e2e10]]] https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/832999[CCS/CC1350STK: Empty project debug session not as expected]
* applies to CC2650STK and CC1350STK: I am unable to reproduce the errors mentioned. I suppose that they were related to the usage of the {rTI-5} rathern than the {rTI-6}.

- [[[e2e11]]] https://e2e.ti.com/support/tools/ccs/f/81/t/832755[CCS/CODECOMPOSER: Code Composer Studio 9 Installer hangs on Windows 7 SP1]
* installing the CC13x and CC26xx device support on Windows 7 Pro fails, this is a bug related to the TI emulator driver installation.

- [[[e2e12]]] https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/833000[CCS/CC1350STK: Setting for Power Selection for CC1350STK and for CC2650STK]
* the power selection in the target configuration files of the example projects for the CC2650STK and the CC1350STK are correct, when using {rTI-6}.
The battery/power supply must be removed during debugging.


==== related discussions started by other users


- [[[e2e20]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/766831?CCS-CC2640R2F-INFO-Cortex-M3-0-File-Loader-Memory-write-failed-Timed-out-waiting-for-target-flashloader-to-execute-command-[CCS/CC2640R2F: INFO -- Cortex_M3_0: File Loader: Memory write failed: Timed out waiting for target flashloader to execute command.]
Tags: Connection ....

- [[[e2e21]]]  https://e2e.ti.com/support/tools/ccs/f/81/t/578693[CCS/CC2650: Memory write failed: Timed out waiting for target to halt]

- [[[e2e22]]]  https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/803609?CCS-CC2640-The-program-works-perfectly-on-first-launch-but-has-Memory-write-failed-error-on-the-next-launch-[CCS/CC2640: The program works perfectly on first launch, but has "Memory write failed" error on the next launch.]

- [[[e2e23]]] https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/744902?CCS-CC2652R-Cant-run-ble5-simple-central-cc2640r2lp-app[CCS/CC2652R: Cant run ble5_simple_central_cc2640r2lp_app]
