
== Introduction
:rMQ-1: https://www.ibm.com/support/knowledgecenter/SSQP8H/iot/platform/reference/mqtt/index.html[MQTT messaging]
:rIB-1: https://cloud.ibm.com[IBM Bluemix]
:fn-diff: footnote:[I am not sure what exactly the difference is.]

{rIB-1} offers a cloud service called _IBM Cloud_ or
_IBM Bluemix_.{fn-diff}
Several plans are available, I will use the _Lite Plan_ also known as the _Free Plan_.


Bluemix provides _Cloud Foundry_, a Platform-as-a-Service infrastructure
that will allow us to run our application and a database without any installation chores. Bluemix also provides
the IBM Watson IoT Platform, hereafter referred to as _IoT Platform_.
This is the central communication hub for {rMQ-1}.
Devices can publish messages and subscribe to commands emitted by application.

{rNR-1} is a programming environment specifically designed for IoT requirements.

I first created an account on IBM Bluemix (with the Lite/Free Plan) and subsequently went
 through the following steps:

. understand the required terminology
. survive credentials hell
. set up a git repo where your code will reside
. develop and test the application locally
. deploy the application to bluemix
. test my work on the desktop (rather than in the cloud).

The application, also known as the _app_ hereafter, is based on this https://developer.ibm.com/tutorials/iot-edge3[IBM developer tutorial] albeit in a simplified form.
The motivation for adopting the work flow discussed in this tutorial is derived from two posts by Nick O'Leary:

* https://knolleary.net/2018/06/01/creating-a-node-red-deployment-pipeline-to-ibm-cloud/[Creating a Node-RED deployment pipeline to IBM Cloud]
* https://knolleary.net/2018/06/05/connecting-to-ibm-cloud-services-from-node-red[Connecting to IBM Cloud services from Node-RED]

The main difference with respect to the first link is that Bluemix now provides an
integrated Continuous Delivery Toolchain, which I use in my setup.
