
== Install local software

Before we start to develop our app, we need to install the Node-RED stack as well as the
IBM Cloud (CLI).

NOTE: This tutorial has been tested on Linux Mint 18.

=== Node-RED

There are many ways to install Node-RED. I choose the
https://github.com/nodesource/distributions/blob/master/README.md[following]:

[source,bash]
----
$ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo npm install -g node-red <1>
$ sudo npm install -g mqtt <2>
----
<1> This might result in:
{sp} +
`gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/node-red/node_modules/bcrypt/.node-gyp'`
{sp} +
I used the `--unsafe-perm` option to fix the https://github.com/nodejs/node-gyp/issues/1619[problem]:
{sp} +
`$ sudo npm install -g --unsafe-perm node-red`
{sp} +
<2> since the test client uses the `require` mechanism and you installed the `mqtt` module globally,
your `NODE_PATH` must include the global `node_modules` directory tree, for example:
{sp} +
`export NODE_PATH=/usr/lib/node_modules`
{sp} +


The later node module is required for the mqtt test client.

We also need `node-red-admin` to generate a password hash:

[listing]
$ sudo npm install -g node-red-admin

=== Bluemix CLI

The IBM Cloud Command Line Interface (CLI) is a tool that lets you monitor all aspects of
the remote infrastructure from your local terminal.
The most important function for this tutorial is the visualization of log files.

To install IBM Cloud CLI
https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started[start here].
