
== Install local software

Before we start to develop our app, we need to install the Node-RED stack as well as the
IBM Cloud (CLI).

NOTE: This tutorial has been tested on Linux Mint 18.

=== Node-RED

There are many ways to install Node-RED. I choose the
https://github.com/nodesource/distributions/blob/master/README.md[following]:

[listing]
$ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo npm install -g node-red
$ npm install -g mqtt

The later node module is required for the mqtt test client.

We also need `node-red-admin` to generate a password hash:

[listing]
$ sudo npm install -g node-red-admin

=== Bluemix CLI

The IBM Cloud Command Line Interface (CLI) is a tool that lets you monitor all aspects of
the remote infrastructure from your local terminal.
The most important function for this tutorial is the visualization of log files.

To install IBM Cloud CLI
https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started[start here].
