= RB3: TIDC-01002
:includedir: _includes
:imagesdir: ./images
:icons: font
:toc: left
:nofooter:
:source-highlighter: highlightjs
:sectnums:
// Refs:
// IBM
:rIB-1: https://cloud.ibm.com[IBM Bluemix]
// TI
:rTI-1: http://www.ti.com/tool/TIDC-01002?jktype=design[SimpleLink™ Sub-1 GHz Sensor to Cloud Gateway Reference Design for TI-RTOS Systems]
:rTI-2: http://www.ti.com/lit/ug/tidud09a/tidud09a.pdf[TI Designs:TIDC-01002 Sub-1GHz Embedded Sensor to Cloud Industrial Internet of Things(IoT) Gateway Reference Design]

[abstract]
icon:home[link="https://vittali.ch"]

NOTE: Work in Progress

In this tutorial I will create the required infrastructure and develop a small application with a
gui and a database backend accessible on the internet.
The project files can be cloned from this https://github.com/vittali/vittali.ch-gst.rb3[git repo].


Sensor and Collector - TI 15.4-Stack Project Zero : see issue with frequency <ref> and doc <ref>


References

CC1352P1

Frequency and channel selection

https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/848811


http://www.ti.com/lit/an/swra048/swra048.pdf[ISM-Band and Short Range Device Regulatory Compliance
Overview]

CC3220SF

SimpleLink™ Wi-Fi® CC3220SF wireless microcontroller LaunchPad™ development kit[http://www.ti.com/tool/CC3220SF-LAUNCHXL]

CC3220SimpleLink™ Wi-Fi®LaunchPad™ DevelopmentKit Hardware[http://www.ti.com/lit/ug/swru463b/swru463b.pdf]


Documentation Overview for SimpleLink™ CC32xx SDK[http://software-dl.ti.com/ecs/SIMPLELINK_CC32XX_SDK/3_30_01_02/exports/docs/Documentation_Overview.html]

Documentation Overview for CC32XX Watson IoT Plugin[http://software-dl.ti.com/targetcontent/watsoniot/1_20_00_04/exports/watson_cc32xx_1_20_00_04/docs/Documentation_Overview.html]
