= RB2: TIDEP0084
:includedir: _includes
:imagesdir: ./images
:icons: font
:toc: left
:nofooter:
:source-highlighter: highlightjs
:sectnums:

// Refs:
// IBM
:rIB-1: https://cloud.ibm.com[IBM Bluemix]
// TI
:rTI-1: http://www.ti.com/tool/TIDEP0084?jktype=design[Sub-1 GHz Sensor to Cloud Industrial IoT Gateway Reference Design for Linux Systems]
:rTI-2: http://www.ti.com/lit/ug/tiduci9c/tiduci9c.pdf[TI Designs:TIDEP0084 Sub-1 GHz Sensor-to-Cloud Industrial Internet-of-Things (IoT) Gateway Reference Design]
// Node-RED
:rNR-1: https://nodered.org[Node-RED]

[abstract]
icon:home[link="https://vittali.ch"]

NOTE: Work in Progress

== Intro

This tutorial is based on {rTI-1}.
The project files can be cloned icon:github[link=https://github.com/vittali/vittali.ch-gst.rb2].

Make sure to configure networking correctly, for example wireless and wired to the BBB, it must be on another network and routes must be configured.
https://askubuntu.com/questions/10741/how-to-set-up-dual-wired-and-wireless-connections/11084




Debian uses connman to manage the network, the settings in /etc/network/interfaces are ignored.

NOTE:: this is not relevant, the debian thing is what is preinstalled on the eemc.

[listing]
debian@beaglebone:~$ sudo cat /var/lib/connman/ethernet_c4f3129bed5b_cable/settings
{blank}[ethernet_c4f3129bed5b_cable]
Name=Wired
AutoConnect=true
Modified=2016-01-24T22:42:30.393712Z
IPv4.method=manual
IPv4.netmask_prefixlen=24
IPv4.local_address=192.168.2.2
IPv4.gateway=192.168.1.1
IPv6.method=auto
IPv6.privacy=disabled


I used the non-docker image (2)
Do not use a USB hub to connect the BBB to the host.

To be sure to auto boot from the SD card
[listing]
sudo dd if=/dev/zero of=/dev/mmcblk1 bs=1024 count=1024



== References

* http://software-dl.ti.com/processor-sdk-linux/esd/docs/latest/linux/Overview_Getting_Started_Guide.html[Processor SDK Linux]

* http://software-dl.ti.com/processor-sdk-linux/esd/docs/latest/linux/index.html[Processor SDK Linux Software Developer’s Guide]
